name: Build and lint code
on:
  pull_request:
    types: [synchronize, opened]
jobs:
  build-and-lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
      - name: Run linter
        run: bun lint
      - name: Build the code
        run: bun build
      